import XCTest
@testable import CsoundStudioCore

final class LilyPondExporterTests: XCTestCase {
    func testMakeLilyWithNoILinesProducesDefaultNoteAndHeader() {
        let csd = """
        <CsoundSynthesizer>
        <CsInstruments>
        instr 1
          a1 oscili 0.5, 440
          out a1
        endin
        </CsInstruments>
        <CsScore>
        ; no i-lines
        e
        </CsScore>
        </CsoundSynthesizer>
        """
        let ly = LilyPondExporter.makeLily(from: csd, tempoBPM: 120)
        XCTAssertTrue(ly.contains("% Generated by CsoundStudio"))
        XCTAssertTrue(ly.contains("\\header { title = \"Composition\""))
        XCTAssertTrue(ly.contains("\\tempo 4 = 120"))
        // Expect at least a single default quarter note token in the body
        XCTAssertTrue(ly.contains("4"))
    }

    func testMakeLilyWithILinesYieldsNotes() {
        let csd = """
        <CsoundSynthesizer>
        <CsInstruments>
        instr 1
          a1 oscili 0.5, 660
          out a1
        endin
        </CsInstruments>
        <CsScore>
        i 1 0 0.5
        i 1 0.5 0.25
        e
        </CsScore>
        </CsoundSynthesizer>
        """
        let ly = LilyPondExporter.makeLily(from: csd, tempoBPM: 120)
        // Should include two duration tokens (e.g., 4 or 8.)
        // We don't assert exact pitch; just that multiple notes are emitted.
        let bodyStart = ly.range(of: "{")?.upperBound ?? ly.startIndex
        let body = String(ly[bodyStart...])
        let tokens = body.split{ $0 == "{" || $0 == "}" || $0.isWhitespace }
        XCTAssertGreaterThanOrEqual(tokens.count, 2)
    }
}
