import XCTest
@testable import CsoundStudioCore

final class LilyPondEngraveErrorTests: XCTestCase {
    func testEngraveReturnsFalseWhenLilyPondUnavailable() throws {
        // Create a minimal .ly file (won't be used if lilypond is unavailable)
        let tmp = URL(fileURLWithPath: NSTemporaryDirectory()).appendingPathComponent("engrave_test_\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: tmp, withIntermediateDirectories: true)
        let lyURL = tmp.appendingPathComponent("score.ly")
        try "% Generated by test\n{ c'4 }\n".write(to: lyURL, atomically: true, encoding: .utf8)

        // Temporarily clear PATH so "/usr/bin/env lilypond" cannot find lilypond,
        // making the test independent of host binaries.
        #if canImport(Darwin)
        let oldPath = getenv("PATH").flatMap { String(cString: $0) } ?? ""
        XCTAssertEqual(setenv("PATH", "", 1), 0)
        defer { _ = setenv("PATH", oldPath, 1) }
        #endif

        let ok = LilyPondExporter.engrave(lyURL: lyURL)
        XCTAssertFalse(ok)
    }
}

