% Generated by HelloCsound duo export
\version "2.24.0"
\header { title = "Motif + Pedal" tagline = "FountainAI • Csound • LilyPond" }
<< 
  { 
    \tempo 4 = 120 
    a'8. b'8. c''4 
  } \ 
  { 
    a'2. 
  } 
>>