name: Swift Tutorials CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-and-test:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        tutorial:
          - 01-hello-fountainai
          - 02-basic-ui-teatro
          - 03-data-persistence-fountainstore
          - 04-multimedia-midi2
          - 05-ai-integration-openapi
          - 06-screenplay-editor-capstone
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show Swift version
        run: swift --version

      - name: Setup tutorial scaffold
        working-directory: tutorials/${{ matrix.tutorial }}
        run: |
          chmod +x setup.sh
          ./setup.sh

      - name: Build
        working-directory: tutorials/${{ matrix.tutorial }}
        run: swift build

      - name: Test
        working-directory: tutorials/${{ matrix.tutorial }}
        run: swift test

